fieldLayouts:
  741edb78-e490-4426-a3ca-1f7033331ddf:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 722dd964-b9a0-4b55-b413-f2954c98c88c
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 41c55707-eb57-4e6b-850e-4f5633162efc
            warning: null
            width: 100
          -
            fieldUid: eb6b24cc-83d7-416f-be4b-d002c7688b58 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca3b1106-e7ed-44cd-a8bd-07bcf5075443
            warning: null
            width: 100
        name: Content
        uid: 22529198-b0c8-440f-aa3e-f169a9e3f551
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: imagesTransforms
transformSubpath: images
