fieldLayouts:
  6e5b9279-e821-4871-a89d-39660a84f991:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 14bfe0e3-f9d0-439b-9005-0711f136dd25
            warning: null
            width: 100
        name: Content
        uid: 42d432b0-8a0a-4d01-9180-8bad74641bf1
fs: $TEMP_IMAGES_FS
handle: tempImages
name: 'Temp Images'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: $IMAGE_TRANSFORM_FS
transformSubpath: tempimages
