columnSuffix: wrkbqypg
contentColumnType: string(255)
fieldGroup: 169ccd00-9c12-4921-b187-8ef8ca2ad525 # Assets
handle: altText
instructions: ''
name: 'Alt Text'
searchable: false
settings:
  byteLimit: 255
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
