dateModified: 1602145624
email:
  fromEmail: '@EMAIL_ADDRESS'
  fromName: '@EMAIL_SENDER'
  replyToEmail: null
  template: null
  transportSettings:
    encryptionMethod: tls
    host: '@SMTP_HOST'
    password: '@SMTP_PASSWORD'
    port: '@SMTP_PORT'
    timeout: '10'
    useAuthentication: '1'
    username: '@SMTP_USER'
  transportType: craft\mail\transportadapters\Smtp
system:
  edition: solo
  live: true
  name: '@SYSTEM_NAME'
  schemaVersion: 3.5.13
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
