assets:
  tempSubpath: temp
  tempVolumeUid: 5a0be839-14a2-465e-a504-bb63dd0281e9 # Images
dateModified: 1647185570
elementSources:
  craft\elements\Asset:
    -
      key: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      tableAttributes:
        - imageSize
        - dateModified
        - link
      type: native
  craft\elements\Entry:
    -
      key: '*'
      tableAttributes:
        - section
        - postDate
        - author
        - link
      type: native
    -
      key: singles
      type: native
    -
      key: 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
      tableAttributes:
        - drafts
        - type
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - postDate
        - author
        - link
      type: native
email:
  fromEmail: $EMAIL_ADDRESS
  fromName: $EMAIL_SENDER
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: $SMTP_ENCRYPTION_METHOD
    host: $SMTP_HOST
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
  imagesTransforms:
    hasUrls: true
    name: 'Images Transforms'
    settings:
      path: '@webroot/transforms'
    type: craft\fs\Local
    url: '@web/transforms'
meta:
  __names__:
    3bb09a1c-cb36-438e-b8d5-0b35b0965f4e: $SYSTEM_NAME # $SYSTEM_NAME
    3e35a043-a62e-4ede-acd6-44dfb92d6914: 'Site Name' # Site Name
    4b050685-0425-4094-bde2-85e2eedd0e12: Text # Text
    5a0be839-14a2-465e-a504-bb63dd0281e9: Images # Images
    5b0c38db-9ab4-47d8-b4a7-913710c08ca6: $SYSTEM_NAME # $SYSTEM_NAME
    7df417e8-1eea-46d8-85a7-2a20370a881e: 'Featured Image' # Featured Image
    9e2e3c4b-bd17-46b3-97f0-a4f6605b93d9: Text # Text
    81e6a0d6-13c5-47ad-a9e6-c2181276db9c: Text # Text
    84b98802-2548-4aed-b67e-fc97f6ed9e30: Page # Page
    169ccd00-9c12-4921-b187-8ef8ca2ad525: Assets # Assets
    735b5e6e-8026-4de4-8e32-14e03d975565: Image # Image
    6856c92d-c593-4425-8886-27e609d74667: Home # Home
    69164545-5879-454d-a57e-f703ca431331: Image # Image
    85898001-9c9c-4d46-abf9-a928e44f0d48: 'Body Content' # Body Content
    abefa0bd-6b36-4b4f-a9de-a4304e7b66a3: 'Public Schema' # Public Schema
    ac457f93-1a50-473e-9983-a899a7f0bed7: Heading # Heading
    bd76fb6e-8765-41d3-8e8a-02e37e127c80: Common # Common
    c780bb7a-337c-46ba-95c4-c0dcbfcb457d: Home # Home
    c752550e-4c4a-4004-8229-7473dcf75450: 'Site Info' # Site Info
    d50026f3-a236-4ae2-b00a-af55076acd17: Site # Site
    eb6b24cc-83d7-416f-be4b-d002c7688b58: Copyright # Copyright
    fbf00eb2-4a16-40ca-96bb-3fadd2bf459c: Default # Default
system:
  edition: pro
  live: false
  name: $SYSTEM_NAME
  retryDuration: 30
  schemaVersion: 4.0.0.5
  timeZone: $SYSTEM_TIMEZONE
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: ''
  photoSubpath: user_photos
  photoVolumeUid: 5a0be839-14a2-465e-a504-bb63dd0281e9 # Images
  requireEmailVerification: true
  validateOnPublicRegistration: false
