dateModified: 1627660713
email:
  fromEmail: '@EMAIL_ADDRESS'
  fromName: '@EMAIL_SENDER'
  replyToEmail: null
  template: null
  transportSettings:
    encryptionMethod: tls
    host: '@SMTP_HOST'
    password: '@SMTP_PASSWORD'
    port: '@SMTP_PORT'
    timeout: '10'
    useAuthentication: '1'
    username: '@SMTP_USER'
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    5b0c38db-9ab4-47d8-b4a7-913710c08ca6: Project # Project
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: 30
  schemaVersion: 3.7.7
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
