fieldLayouts:
  f4019294-72d3-498d-a196-72612042deb5:
    tabs:
      -
        elements:
          -
            fieldUid: 3e35a043-a62e-4ede-acd6-44dfb92d6914 # Site Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f6b964a-7458-4e96-bbf6-7d922977be65
            warning: null
            width: 100
          -
            fieldUid: eb6b24cc-83d7-416f-be4b-d002c7688b58 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edb4663c-ed87-4c0d-80ee-fa175abb697c
            warning: null
            width: 100
        name: Content
        uid: 5e034a3c-8cf7-46cb-a494-076274149e80
handle: siteInfo
name: 'Site Info'
sortOrder: 1
